export const ACTION_STATUS_VALUES = [
    "REPONDU",
    "PAS_DE_REPONSE",
    "NUMERO_INVALIDE",
    "INTERESSE",
    "NON_INTERESSE",
    "A_RAPPELER",
    "A_VOIR_AUTRE_CONTACT",
    "REMPLIRA_FORMULAIRE",
    "NON_INTERESSE_APRES_RELANCE",
    "CHANGER_CONTACT",
    "CONFIRMATION_RECU",
    "AUTRE",
  ];